const { v4: uuidv4 } = require("uuid");

module.exports = [
	{
		id: uuidv4(),
		title: "Rent",
		amount: 2500,
		category: "Housing",
		description: "Monthly rent",
		date: "2022-01-01",
	},
	{
		id: uuidv4(),
		title: "Groceries",
		amount: 400,
		category: "Food",
		description: "Weekly groceries",
		date: "2022-01-15",
	},
	{
		id: uuidv4(),
		title: "Electricity",
		amount: 200,
		category: "Utilities",
		description: "Monthly electricity bill",
		date: "2022-02-01",
	},
	{
		id: uuidv4(),
		title: "Internet",
		amount: 600,
		category: "Utilities",
		description: "Monthly internet bill",
		date: "2022-02-15",
	},
	{
		id: uuidv4(),
		title: "Car Insurance",
		amount: 300,
		category: "Insurance",
		description: "Quarterly car insurance payment",
		date: "2022-02-20",
	},
	{
		id: uuidv4(),
		title: "Gas",
		amount: 240,
		category: "Transportation",
		description: "Bi-weekly gas for car",
		date: "2022-03-01",
	},
	{
		id: uuidv4(),
		title: "Gym Membership",
		amount: 100,
		category: "Health",
		description: "Monthly gym membership",
		date: "2022-03-15",
	},
	{
		id: uuidv4(),
		title: "Dinner Out",
		amount: 100,
		category: "Entertainment",
		description: "Dinner at a restaurant",
		date: "2022-04-01",
	},
];
