const { v4: uuidv4 } = require("uuid");

module.exports = [
	{
		id: uuidv4(),
		title: "Rent",
		amount: 2500,
		category: "housing",
		description: "Monthly rent",
		date: "2022-01-01",
	},
	{
		id: uuidv4(),
		title: "Groceries",
		amount: 400,
		category: "food",
		description: "Weekly groceries",
		date: "2022-01-15",
	},
	{
		id: uuidv4(),
		title: "Electricity",
		amount: 200,
		category: "other",
		description: "Monthly electricity bill",
		date: "2022-02-01",
	},
	{
		id: uuidv4(),
		title: "Internet",
		amount: 600,
		category: "other",
		description: "Monthly internet bill",
		date: "2022-02-15",
	},
	{
		id: uuidv4(),
		title: "University Tuition",
		amount: 6000,
		category: "education",
		description: "Semester tuition fee",
		date: "2022-02-20",
	},
	{
		id: uuidv4(),
		title: "Netflix Subscription",
		amount: 15,
		category: "subscriptions",
		description: "Monthly Netflix subscription",
		date: "2022-03-01",
	},
	{
		id: uuidv4(),
		title: "Gym Membership",
		amount: 100,
		category: "health",
		description: "Monthly gym membership",
		date: "2022-03-15",
	},
	{
		id: uuidv4(),
		title: "Flight Ticket",
		amount: 200,
		category: "travelling",
		description: "Bought a flight ticket for vacation",
		date: "2022-04-01",
	},
];
