const { v4: uuidv4 } = require("uuid");

module.exports = [
	{
		id: uuidv4(),
		title: "Rent",
		amount: 1000,
		category: "Housing",
		description: "Monthly rent",
		date: "2022-01-01",
	},
	{
		id: uuidv4(),
		title: "Groceries",
		amount: 200,
		category: "Food",
		description: "Weekly groceries",
		date: "2022-01-02",
	},
	{
		id: uuidv4(),
		title: "Electricity",
		amount: 100,
		category: "Utilities",
		description: "Monthly electricity bill",
		date: "2022-01-05",
	},
	{
		id: uuidv4(),
		title: "Internet",
		amount: 50,
		category: "Utilities",
		description: "Monthly internet bill",
		date: "2022-01-10",
	},
	{
		id: uuidv4(),
		title: "Car Insurance",
		amount: 150,
		category: "Insurance",
		description: "Quarterly car insurance payment",
		date: "2022-01-15",
	},
	{
		id: uuidv4(),
		title: "Gas",
		amount: 60,
		category: "Transportation",
		description: "Bi-weekly gas for car",
		date: "2022-01-20",
	},
	{
		id: uuidv4(),
		title: "Gym Membership",
		amount: 30,
		category: "Health",
		description: "Monthly gym membership",
		date: "2022-01-25",
	},
	{
		id: uuidv4(),
		title: "Dinner Out",
		amount: 100,
		category: "Entertainment",
		description: "Dinner at a restaurant",
		date: "2022-01-30",
	},
];
