module.exports = [
	{
		id: 1,
		title: "Salary",
		amount: 5000,
		category: "Job",
		description: "Monthly salary",
		date: "2022-01-01",
	},
	{
		id: 2,
		title: "Freelance",
		amount: 2000,
		category: "Job",
		description: "Freelance project",
		date: "2022-01-15",
	},
	{
		id: 3,
		title: "Bonus",
		amount: 1000,
		category: "Job",
		description: "Yearly bonus",
		date: "2022-02-01",
	},
	{
		id: 4,
		title: "Investment",
		amount: 3000,
		category: "Investment",
		description: "Investment return",
		date: "2022-02-15",
	},
	{
		id: 5,
		title: "Rental",
		amount: 1500,
		category: "Property",
		description: "Monthly rental income",
		date: "2022-02-20",
	},
	{
		id: 6,
		title: "Dividends",
		amount: 1200,
		category: "Investment",
		description: "Quarterly dividends",
		date: "2022-03-01",
	},
	{
		id: 7,
		title: "Lottery",
		amount: 50000,
		category: "Other",
		description: "Lottery prize",
		date: "2022-03-15",
	},
	{
		id: 8,
		title: "Gift",
		amount: 500,
		category: "Other",
		description: "Birthday gift",
		date: "2022-04-01",
	},
];
