const { v4: uuidv4 } = require("uuid");

module.exports = [
	{
		id: uuidv4(),
		title: "Salary",
		amount: 5000,
		category: "salary",
		description: "Monthly salary",
		date: "2022-01-01",
	},
	{
		id: uuidv4(),
		title: "Freelance",
		amount: 2000,
		category: "freelancing",
		description: "Freelance project",
		date: "2022-01-15",
	},
	{
		id: uuidv4(),
		title: "Bonus",
		amount: 1000,
		category: "salary",
		description: "Yearly bonus",
		date: "2022-02-01",
	},
	{
		id: uuidv4(),
		title: "Investment",
		amount: 3000,
		category: "investments",
		description: "Investment return",
		date: "2022-02-15",
	},
	{
		id: uuidv4(),
		title: "Rental",
		amount: 1500,
		category: "property",
		description: "Monthly rental income",
		date: "2022-02-20",
	},
	{
		id: uuidv4(),
		title: "Dividends",
		amount: 1200,
		category: "investments",
		description: "Quarterly dividends",
		date: "2022-03-01",
	},
	{
		id: uuidv4(),
		title: "Lottery",
		amount: 5000,
		category: "other",
		description: "Lottery prize",
		date: "2022-03-15",
	},
	{
		id: uuidv4(),
		title: "Gift",
		amount: 500,
		category: "other",
		description: "Birthday gift",
		date: "2022-04-01",
	},
];
